# Generated by Django 4.0.4 on 2022-04-29 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('slug', models.SlugField()),
                ('category', models.CharField(choices=[('world', 'World'), ('environment', 'Environment'), ('technology', 'Technology'), ('design', 'Design'), ('business', 'Business'), ('politics', 'Politics'), ('science', 'Science'), ('opinion', 'Opinion'), ('travel', 'Travel')], default='world', max_length=20)),
                ('thumbnail', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('exercept', models.CharField(max_length=200)),
                ('month', models.CharField(max_length=3)),
                ('day', models.CharField(max_length=2)),
                ('content', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
